/*SHWETA PLEASE PLACE YOUR CSS CODE IN HERE*/
/* General Classes */

.btn-grey{
    color: #fff;
    background-color: #979797;
}
.btn-white{
    background-color: #fff;
    border: 1px solid #B4B4B4;
    color: #828080;
}
.form-horizontal .form-control{
    height: 50px;
    width: 360px;
    padding: 25px 15px 5px 15px;
    border-color: #999;
    color: #545454;
    font-size: 16px;
}
.suntrust-app-nav-list > li.active:after{
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 0 8px 8px 8px;
    border-color: transparent transparent #FFF transparent;
    line-height: 0px;
    _border-color: #000000 #000000 #fff #000000;
    _filter: progid:DXImageTransform.Microsoft.Chroma(color='#000000');
    bottom: -4px;
    left: 50%;
    content: "";
    position: absolute;
    margin-left: -10px;
}
.page .main-headingArea{
    border-bottom: 1px solid #999;
    border-radius: 1px;
    height: 80px;
}
.page .main-heading{
    font-size: 28px;
    font-weight: 200;
    padding:30px 20px 20px 0px;
    margin: 0px;
    text-align: left;
}
.page .main-heading span{
    font-size: 20px;
    color: #828080;
    font-weight: 200;
}
.close-btnArea{
    padding-top: 30px;
    font-weight: 200;
}
.btn-close{
    padding: 2px 5px;
    font-size: 20px;
    line-height: 18px;
    margin-left: 8px;
}
.page nav.inner-sub-nav{
    height: 50px;
    margin-bottom:0px;
}
.page nav.inner-sub-nav ul{
    margin:0 -15px;
}
.page nav.inner-sub-nav li{
    display: inline-block;
}
.page nav.inner-sub-nav li a{
    padding: 10px 15px;
    text-decoration: underline;
    color: #828080;
    line-height: 25px;
}
.page nav.inner-sub-nav .sub-nav-Btn{
    margin: 6px 0;
}
.page nav.inner-sub-nav .inner-sub-nav-Btn .btn-white{
    margin-right: 38px;
}
.manageprofile-area{
    position: relative;
}
.manageprofile-area .custom-overlay{
    position: absolute;
    background: #fff;
    opacity: 0.5;
    width: 100%;
    height: 100%;
    top: 0;
}
.manage-profile{
    padding-left: 30px;
    padding-right: 30px;
}
.manage-profile .section-heading{
    width: 100%;
    float: left;
    margin-top:10px;
    border-bottom: 1px solid #DDD;
    border-radius: 1px;
}
.manage-profile .section-heading .section-heading-inner{
    padding:0px;
}
.manage-profile .section-heading h3{
    color: #828080;
    font-size:20px;
    font-weight: 200;
}
.manage-profile .section-heading .btn-white{
    margin: 10px 0;
}
.manage-profile .section .form-horizontal{
    margin-top: 20px;
    width: 100%;
    float: left;
    color: #828080;
    font-weight: 200;
}
.manage-profile .section .form-horizontal .form-group{
    margin-bottom: 20px;
}
.manage-profile .section .form-horizontal .application-content{
    position: relative;
    border-bottom: 1px solid #DDD;
    border-radius: 1px;
}
.manage-profile .section .form-horizontal .application-content .inner-content{
    padding-right: 100px;
    width:100%;
    padding-bottom: 15px;
}
.manage-profile .section .form-horizontal .application-content .inner-content span{
    display: block;
    color:#DDD;
}
.manage-profile .section .form-horizontal .application-content .btn{
    position: absolute;
    right: 15px;
    top: 0px;
}
.custom-popup{
    border: 2px solid #979797;
    margin: 15px 0 0 0;
    border-radius: 4px;
    z-index: 1;
}
.custom-popup .popup-headingArea{
    border-bottom: 1px solid #DDD;
    border-radius: 1px;
    padding: 15px 0px;
}
.custom-popup .popup-headingArea h4{
    color: #545454;
    font-size: 20px;
    margin:0px;
}
.custom-popup .close-circlebtnArea{
    margin-right: 38px;
    margin-top: 7px;
    cursor: pointer;
}
.custom-popup .close-circlebtnArea .btn-circleclose{
    border-radius: 50%;
    padding: 0px 4px;
    font-size: 12px;
    line-height: 16px;
}
/*.custom-popup .popup-content{
    float: left;
    width: 100%;
}*/
.custom-popup .popup-content .popup-content-heading{
    border-bottom: 1px solid #999;
    border-radius: 1px;
    padding: 20px 0px 5px 0;
}
.custom-popup .popup-content .popup-content-heading h5{
    color: #545454;
    font-size: 16px;
    line-height: 22pt;
    margin: 0px;
}
.custom-popup .popup-content .form-horizontal .form-group{
    margin-bottom: 10px;
    position: relative;
}
.custom-popup .popup-content .form-horizontal .small-text{
    font-size: 12px;
    line-height: 16px;
    color: #878787;
    display: block;
    padding: 7px 15px;
    z-index: 2;
}
.manage-profile .section .custom-popup .popup-content .form-horizontal{
    width: auto;
    margin-bottom: 30px;
}
.custom-popup .popup-content .form-horizontal label{
    position: absolute;
}
.custom-popup .popup-content .form-horizontal span.small-text{
    position: absolute;
    right: 25px;
    z-index: 9;
    top: 10px;
    color: #999;
    font-size: 14px;
}
.custom-popup .popup-content .form-horizontal select.form-control{
    padding-left: 10px;
}
.custom-popup .popup-content .form-horizontal .custom-select select.form-control{
    position: relative;
    padding-top: 10px;
    color: #999;
    font-size: 16px;
}
.custom-popup .popup-content .form-horizontal .form-control.placeholder-field{
    padding-top: 7px;
}
.custom-popup .popup-footer{
    border-top: 1px solid #999;
    border-radius: 1px;
    padding: 20px 0px;
    display: inline-block;
    width: 100%;
}
.add-anthrNo{
    text-decoration:underline;
    margin: -10px 0 20px 0;
    padding: 0;
}
.custom-popup .popup-content .steps{
    margin: 20px 0;
    width: 100%;
    float: left;
}
.custom-popup .popup-content .steps ul{
    margin:0px;
}
.custom-popup .popup-content .steps ul li{
    width: 33.3%;
    padding: 0;
    margin: 0;
    float: left;
    position: relative;
}
.custom-popup .popup-content .steps ul li a{
    background: #efefef;
    display: inline-block;
    margin-right: 5px;
    min-width: 150px;
    outline: none;
    padding: 10px 40px 10px;
    position: relative;
    text-decoration: none;
}
.custom-popup .popup-content .steps ul li a:before {
    width: 0;
    height: 0;
    border-top: 20px inset transparent;
    border-bottom: 20px inset transparent;
    border-left: 20px solid #fff;
    position: absolute;
    content:"";
    top: 0;
    left: 0;
}
.custom-popup .popup-content .steps ul li a:after {
    width: 0;
    height: 0;
    border-top: 20px inset transparent;
    border-bottom: 20px inset transparent;
    border-left: 21px solid #efefef;
    position: absolute;
    content: "";
    top: 0;
    right: -20px;
    z-index: 2;
}
.custom-popup .popup-content .steps ul li a:first-child:before,
.custom-popup .popup-content .steps ul li a:last-child:after {
    border: none;
}
.custom-popup .popup-content .steps ul li a:first-child {
    -webkit-border-radius: 8px 0 0 0px;
    -moz-border-radius: 8px 0 0 0px;
    border-radius: 8px 0 0 0px;
}
.custom-popup .popup-content .steps ul li a:last-child {
    -webkit-border-radius: 0 8px 0px 0;
    -moz-border-radius: 0 8px 0px 0;
    border-radius: 0 8px 0px 0;
}
/*.custom-popup .popup-content .steps ul li:after{
    right: 0px;
    content: '';
    height: 0;
    display: block;
    border-color:#fff #fff #fff transparent;
    border-width: 25px;
    border-style: solid;
    position: absolute;
    top: 0;
    z-index: 3;
}*/

/*.custom-popup .popup-content .form-horizontal select::before{
    content: '<>';
    font: 11px "Consolas", monospace;
    color: #aaa;
    -webkit-transform: rotate(90deg);
    -moz-transform: rotate(90deg);
    -ms-transform: rotate(90deg);
    transform: rotate(90deg);
    right: 0px;
    top: 2px;
    padding: 0 0 2px;
    border-bottom: 1px solid #ddd;
    position: absolute;
    z-index: 10;
}*/



/*media queries starts*/

@media (max-width: 990px) {

    .manage-profile .section .form-horizontal .form-group{
        margin-right: 0px;
        margin-left: 0px
    }

}